[
	{
		"room_id" : 1,
		"room_availability" : "Available",
		"room_bed_type" : "Twin",
		"room_description" : "Cozy single room with twin beds",
		"room_discount" : 200,
		"room_issue_date" : "2024-05-09",
		"room_price" : 2000,
		"room_residence_ref_id": 2,
		"room_trading_price" : 1800,
		"room_type" : "Single",
		"is_active" : true,
		"room_area" : "200 sq.ft",
		"room_capacity" : 2,
		"room_quantity" : 1
	},
  {
    "room_id": 2,
    "room_availability": "Available",
    "room_bed_type": "Queen",
    "room_description": "Spacious double room with a queen-sized bed",
    "room_discount": 150,
    "room_issue_date": "2024-04-15",
    "room_price": 2500,
    "room_residence_ref_id": 2,
    "room_trading_price": 2350,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "200 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 3,
    "room_availability": "Unavailable",
    "room_bed_type": "King",
    "room_description": "Luxurious suite with a king-sized bed and private balcony",
    "room_discount": 300,
    "room_issue_date": "2024-05-01",
    "room_price": 4000,
    "room_residence_ref_id": 2,
    "room_trading_price": 3700,
    "room_type": "Suite",
    "is_active" : true,
    "room_area": "220 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 4,
    "room_availability": "Available",
    "room_bed_type": "Single",
    "room_description": "Cozy single room with a single bed",
    "room_discount": 100,
    "room_issue_date": "2024-05-20",
    "room_price": 1500,
    "room_residence_ref_id": 2,
    "room_trading_price": 1400,
    "room_type": "Single",
    "is_active" : true,
    "room_area": "180 sq.ft",
    "room_capacity": 1,
    "room_quantity": 1
  },
  {
    "room_id": 5,
    "room_availability": "Available",
    "room_bed_type": "Double",
    "room_description": "Comfortable double room with two single beds",
    "room_discount": 200,
    "room_issue_date": "2024-05-10",
    "room_price": 2200,
    "room_residence_ref_id": 2,
    "room_trading_price": 2000,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "190 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 6,
    "room_availability": "Unavailable",
    "room_bed_type": "Queen",
    "room_description": "Family room with a queen-sized bed and a bunk bed",
    "room_discount": 250,
    "room_issue_date": "2024-04-28",
    "room_price": 2800,
    "room_residence_ref_id": 3,
    "room_trading_price": 2550,
    "room_type": "Family",
    "is_active" : true,
    "room_area": "210 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 7,
    "room_availability": "Available",
    "room_bed_type": "King",
    "room_description": "Elegant room with a king-sized bed and garden view",
    "room_discount": 200,
    "room_issue_date": "2024-05-05",
    "room_price": 3200,
    "room_residence_ref_id": 3,
    "room_trading_price": 3000,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "195 sq.ft",
    "room_capacity": 4,
    "room_quantity": 1
  },
  {
    "room_id": 8,
    "room_availability": "Available",
    "room_bed_type": "Single",
    "room_description": "Compact single room with a single bed and city view",
    "room_discount": 100,
    "room_issue_date": "2024-05-14",
    "room_price": 1800,
    "room_residence_ref_id": 3,
    "room_trading_price": 1700,
    "room_type": "Single",
    "is_active" : true,
    "room_area": "185 sq.ft",
    "room_capacity": 1,
    "room_quantity": 1
  },
  {
    "room_id": 9,
    "room_availability": "Unavailable",
    "room_bed_type": "Double",
    "room_description": "Classic double room with a double bed",
    "room_discount": 150,
    "room_issue_date": "2024-04-25",
    "room_price": 2400,
    "room_residence_ref_id": 3,
    "room_trading_price": 2250,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "205 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 10,
    "room_availability": "Available",
    "room_bed_type": "Queen",
    "room_description": "Charming room with a queen-sized bed and fireplace",
    "room_discount": 200,
    "room_issue_date": "2024-05-18",
    "room_price": 2700,
    "room_residence_ref_id": 3,
    "room_trading_price": 2500,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "198 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 11,
    "room_availability": "Available",
    "room_bed_type": "King",
    "room_description": "Luxurious suite with a king-sized bed and ocean view",
    "room_discount": 300,
    "room_issue_date": "2024-05-22",
    "room_price": 4500,
    "room_residence_ref_id": 4,
    "room_trading_price": 4200,
    "room_type": "Suite",
    "is_active" : true,
    "room_area": "215 sq.ft",
    "room_capacity": 3,
    "room_quantity": 1
  },
  {
    "room_id": 12,
    "room_availability": "Available",
    "room_bed_type": "Queen",
    "room_description": "Cozy room with a queen-sized bed and garden view",
    "room_discount": 200,
    "room_issue_date": "2024-05-25",
    "room_price": 2800,
    "room_residence_ref_id": 4,
    "room_trading_price": 2600,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "200 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 13,
    "room_availability": "Available",
    "room_bed_type": "Double",
    "room_description": "Classic double room with a double bed",
    "room_discount": 250,
    "room_issue_date": "2024-05-23",
    "room_price": 3200,
    "room_residence_ref_id": 4,
    "room_trading_price": 3000,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "195 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 14,
    "room_availability": "Unavailable",
    "room_bed_type": "Single",
    "room_description": "Compact single room with a single bed and city view",
    "room_discount": 100,
    "room_issue_date": "2024-05-24",
    "room_price": 1800,
    "room_residence_ref_id": 4,
    "room_trading_price": 1700,
    "room_type": "Single",
    "is_active" : true,
    "room_area": "185 sq.ft",
    "room_capacity": 1,
    "room_quantity": 1
  },
  {
    "room_id": 15,
    "room_availability": "Available",
    "room_bed_type": "Twin",
    "room_description": "Cozy twin room with two single beds",
    "room_discount": 150,
    "room_issue_date": "2024-05-26",
    "room_price": 2200,
    "room_residence_ref_id": 4,
    "room_trading_price": 2050,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "190 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 16,
    "room_availability": "Available",
    "room_bed_type": "Double",
    "room_description": "Modern double room with a comfortable bed",
    "room_discount": 200,
    "room_issue_date": "2024-05-27",
    "room_price": 2500,
    "room_residence_ref_id": 5,
    "room_trading_price": 2300,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "195 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 17,
    "room_availability": "Available",
    "room_bed_type": "King",
    "room_description": "Luxurious room with a king-sized bed and panoramic view",
    "room_discount": 300,
    "room_issue_date": "2024-05-28",
    "room_price": 3800,
    "room_residence_ref_id": 5,
    "room_trading_price": 3500,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "210 sq.ft",
    "room_capacity": 4,
    "room_quantity": 1
  },
  {
    "room_id": 18,
    "room_availability": "Unavailable",
    "room_bed_type": "Single",
    "room_description": "Cozy single room with a view of the city skyline",
    "room_discount": 100,
    "room_issue_date": "2024-05-29",
    "room_price": 1600,
    "room_residence_ref_id": 5,
    "room_trading_price": 1500,
    "room_type": "Single",
    "is_active" : true,
    "room_area": "180 sq.ft",
    "room_capacity": 1,
    "room_quantity": 1
  },
  {
    "room_id": 19,
    "room_availability": "Available",
    "room_bed_type": "Twin",
    "room_description": "Comfortable twin room with two single beds",
    "room_discount": 150,
    "room_issue_date": "2024-05-30",
    "room_price": 2300,
    "room_residence_ref_id": 5,
    "room_trading_price": 2100,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "200 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 20,
    "room_availability": "Available",
    "room_bed_type": "Queen",
    "room_description": "Charming room with a queen-sized bed and balcony",
    "room_discount": 200,
    "room_issue_date": "2024-06-01",
    "room_price": 2700,
    "room_residence_ref_id": 5,
    "room_trading_price": 2500,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "205 sq.ft",
    "room_capacity": 3,
    "room_quantity": 1
  },
  {
    "room_id": 21,
    "room_availability": "Available",
    "room_bed_type": "Single",
    "room_description": "Compact single room with a cozy atmosphere",
    "room_discount": 100,
    "room_issue_date": "2024-06-02",
    "room_price": 1700,
    "room_residence_ref_id": 6,
    "room_trading_price": 1600,
    "room_type": "Single",
    "is_active" : true,
    "room_area": "185 sq.ft",
    "room_capacity": 1,
    "room_quantity": 1
  },
  {
    "room_id": 22,
    "room_availability": "Available",
    "room_bed_type": "Double",
    "room_description": "Cozy double room with a view of the mountains",
    "room_discount": 150,
    "room_issue_date": "2024-06-03",
    "room_price": 2200,
    "room_residence_ref_id": 6,
    "room_trading_price": 2050,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "190 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 23,
    "room_availability": "Unavailable",
    "room_bed_type": "Queen",
    "room_description": "Charming room with a queen-sized bed and garden view",
    "room_discount": 200,
    "room_issue_date": "2024-06-04",
    "room_price": 2600,
    "room_residence_ref_id": 6,
    "room_trading_price": 2400,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "195 sq.ft",
    "room_capacity": 3,
    "room_quantity": 1
  },
  {
    "room_id": 24,
    "room_availability": "Available",
    "room_bed_type": "King",
    "room_description": "Luxurious room with a king-sized bed and ocean view",
    "room_discount": 250,
    "room_issue_date": "2024-06-05",
    "room_price": 3200,
    "room_residence_ref_id": 6,
    "room_trading_price": 3000,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "200 sq.ft",
    "room_capacity": 3,
    "room_quantity": 1
  },
  {
    "room_id": 25,
    "room_availability": "Available",
    "room_bed_type": "Twin",
    "room_description": "Comfortable twin room with two single beds",
    "room_discount": 150,
    "room_issue_date": "2024-06-06",
    "room_price": 2300,
    "room_residence_ref_id": 6,
    "room_trading_price": 2100,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "205 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 26,
    "room_availability": "Available",
    "room_bed_type": "Double",
    "room_description": "Modern double room with minimalist design",
    "room_discount": 200,
    "room_issue_date": "2024-06-07",
    "room_price": 2400,
    "room_residence_ref_id": 7,
    "room_trading_price": 2200,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "190 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 27,
    "room_availability": "Available",
    "room_bed_type": "King",
    "room_description": "Spacious room with a king-sized bed and panoramic view",
    "room_discount": 250,
    "room_issue_date": "2024-06-08",
    "room_price": 3200,
    "room_residence_ref_id": 7,
    "room_trading_price": 3000,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "200 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 28,
    "room_availability": "Unavailable",
    "room_bed_type": "Single",
    "room_description": "Cozy single room with a view of the city skyline",
    "room_discount": 100,
    "room_issue_date": "2024-06-09",
    "room_price": 1700,
    "room_residence_ref_id": 7,
    "room_trading_price": 1600,
    "room_type": "Single",
    "is_active" : true,
    "room_area": "185 sq.ft",
    "room_capacity": 1,
    "room_quantity": 1
  },
  {
    "room_id": 29,
    "room_availability": "Available",
    "room_bed_type": "Twin",
    "room_description": "Comfortable twin room with two single beds",
    "room_discount": 150,
    "room_issue_date": "2024-06-10",
    "room_price": 2200,
    "room_residence_ref_id": 7,
    "room_trading_price": 2000,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "195 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 30,
    "room_availability": "Available",
    "room_bed_type": "Queen",
    "room_description": "Charming room with a queen-sized bed and balcony",
    "room_discount": 200,
    "room_issue_date": "2024-06-11",
    "room_price": 2700,
    "room_residence_ref_id": 7,
    "room_trading_price": 2500,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "200 sq.ft",
    "room_capacity": 3,
    "room_quantity": 1
  },
  {
    "room_id": 31,
    "room_availability": "Available",
    "room_bed_type": "Single",
    "room_description": "Cozy single room with modern amenities",
    "room_discount": 100,
    "room_issue_date": "2024-06-12",
    "room_price": 1800,
    "room_residence_ref_id": 8,
    "room_trading_price": 1700,
    "room_type": "Single",
    "is_active" : true,
    "room_area": "185 sq.ft",
    "room_capacity": 1,
    "room_quantity": 1
  },
  {
    "room_id": 32,
    "room_availability": "Available",
    "room_bed_type": "Double",
    "room_description": "Spacious double room with a cozy ambiance",
    "room_discount": 150,
    "room_issue_date": "2024-06-13",
    "room_price": 2300,
    "room_residence_ref_id": 8,
    "room_trading_price": 2100,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "190 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 33,
    "room_availability": "Unavailable",
    "room_bed_type": "Queen",
    "room_description": "Elegant room with a queen-sized bed and garden view",
    "room_discount": 200,
    "room_issue_date": "2024-06-14",
    "room_price": 2600,
    "room_residence_ref_id": 8,
    "room_trading_price": 2400,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "195 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 34,
    "room_availability": "Available",
    "room_bed_type": "King",
    "room_description": "Luxurious room with a king-sized bed and ocean view",
    "room_discount": 250,
    "room_issue_date": "2024-06-15",
    "room_price": 3200,
    "room_residence_ref_id": 8,
    "room_trading_price": 3000,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "200 sq.ft",
    "room_capacity": 3,
    "room_quantity": 1
  },
  {
    "room_id": 35,
    "room_availability": "Available",
    "room_bed_type": "Twin",
    "room_description": "Comfortable twin room with two single beds",
    "room_discount": 150,
    "room_issue_date": "2024-06-16",
    "room_price": 2200,
    "room_residence_ref_id": 8,
    "room_trading_price": 2000,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "195 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 36,
    "room_availability": "Available",
    "room_bed_type": "Single",
    "room_description": "Compact single room with a modern design",
    "room_discount": 100,
    "room_issue_date": "2024-06-17",
    "room_price": 1800,
    "room_residence_ref_id": 9,
    "room_trading_price": 1700,
    "room_type": "Single",
    "is_active" : true,
    "room_area": "185 sq.ft",
    "room_capacity": 1,
    "room_quantity": 1
  },
  {
    "room_id": 37,
    "room_availability": "Available",
    "room_bed_type": "Double",
    "room_description": "Spacious double room with a cozy ambiance",
    "room_discount": 150,
    "room_issue_date": "2024-06-18",
    "room_price": 2300,
    "room_residence_ref_id": 9,
    "room_trading_price": 2100,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "190 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 38,
    "room_availability": "Unavailable",
    "room_bed_type": "Queen",
    "room_description": "Elegant room with a queen-sized bed and garden view",
    "room_discount": 200,
    "room_issue_date": "2024-06-19",
    "room_price": 2600,
    "room_residence_ref_id": 9,
    "room_trading_price": 2400,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "195 sq.ft",
    "room_capacity": 3,
    "room_quantity": 1
  },
  {
    "room_id": 39,
    "room_availability": "Available",
    "room_bed_type": "King",
    "room_description": "Luxurious room with a king-sized bed and ocean view",
    "room_discount": 250,
    "room_issue_date": "2024-06-20",
    "room_price": 3200,
    "room_residence_ref_id": 9,
    "room_trading_price": 3000,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "200 sq.ft",
    "room_capacity": 4,
    "room_quantity": 1
  },
  {
    "room_id": 40,
    "room_availability": "Available",
    "room_bed_type": "Twin",
    "room_description": "Comfortable twin room with two single beds",
    "room_discount": 150,
    "room_issue_date": "2024-06-21",
    "room_price": 2200,
    "room_residence_ref_id": 9,
    "room_trading_price": 2000,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "195 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 41,
    "room_availability": "Available",
    "room_bed_type": "Single",
    "room_description": "Compact single room with modern amenities",
    "room_discount": 100,
    "room_issue_date": "2024-06-22",
    "room_price": 1800,
    "room_residence_ref_id": 10,
    "room_trading_price": 1700,
    "room_type": "Single",
    "is_active" : true,
    "room_area": "185 sq.ft",
    "room_capacity": 1,
    "room_quantity": 1
  },
  {
    "room_id": 42,
    "room_availability": "Available",
    "room_bed_type": "Double",
    "room_description": "Spacious double room with a cozy ambiance",
    "room_discount": 150,
    "room_issue_date": "2024-06-23",
    "room_price": 2300,
    "room_residence_ref_id": 10,
    "room_trading_price": 2100,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "190 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 43,
    "room_availability": "Unavailable",
    "room_bed_type": "Queen",
    "room_description": "Elegant room with a queen-sized bed and garden view",
    "room_discount": 200,
    "room_issue_date": "2024-06-24",
    "room_price": 2600,
    "room_residence_ref_id": 10,
    "room_trading_price": 2400,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "195 sq.ft",
    "room_capacity": 3,
    "room_quantity": 1
  },
  {
    "room_id": 44,
    "room_availability": "Available",
    "room_bed_type": "King",
    "room_description": "Luxurious room with a king-sized bed and ocean view",
    "room_discount": 250,
    "room_issue_date": "2024-06-25",
    "room_price": 3200,
    "room_residence_ref_id": 10,
    "room_trading_price": 3000,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "200 sq.ft",
    "room_capacity": 4,
    "room_quantity": 1
  },
  {
    "room_id": 45,
    "room_availability": "Available",
    "room_bed_type": "Twin",
    "room_description": "Comfortable twin room with two single beds",
    "room_discount": 150,
    "room_issue_date": "2024-06-26",
    "room_price": 2200,
    "room_residence_ref_id": 10,
    "room_trading_price": 2000,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "195 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 46,
    "room_availability": "Available",
    "room_bed_type": "Single",
    "room_description": "Compact single room with modern amenities",
    "room_discount": 100,
    "room_issue_date": "2024-06-27",
    "room_price": 1800,
    "room_residence_ref_id": 11,
    "room_trading_price": 1700,
    "room_type": "Single",
    "is_active" : true,
    "room_area": "185 sq.ft",
    "room_capacity": 1,
    "room_quantity": 1
  },
  {
    "room_id": 47,
    "room_availability": "Available",
    "room_bed_type": "Double",
    "room_description": "Spacious double room with a cozy ambiance",
    "room_discount": 150,
    "room_issue_date": "2024-06-28",
    "room_price": 2300,
    "room_residence_ref_id": 11,
    "room_trading_price": 2100,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "190 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  },
  {
    "room_id": 48,
    "room_availability": "Unavailable",
    "room_bed_type": "Queen",
    "room_description": "Elegant room with a queen-sized bed and garden view",
    "room_discount": 200,
    "room_issue_date": "2024-06-29",
    "room_price": 2600,
    "room_residence_ref_id": 11,
    "room_trading_price": 2400,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "195 sq.ft",
    "room_capacity": 3,
    "room_quantity": 1
  },
  {
    "room_id": 49,
    "room_availability": "Available",
    "room_bed_type": "King",
    "room_description": "Luxurious room with a king-sized bed and ocean view",
    "room_discount": 250,
    "room_issue_date": "2024-06-30",
    "room_price": 3200,
    "room_residence_ref_id": 11,
    "room_trading_price": 3000,
    "room_type": "Deluxe",
    "is_active" : true,
    "room_area": "200 sq.ft",
    "room_capacity": 3,
    "room_quantity": 1
  },
  {
    "room_id": 50,
    "room_availability": "Available",
    "room_bed_type": "Twin",
    "room_description": "Comfortable twin room with two single beds",
    "room_discount": 150,
    "room_issue_date": "2024-07-01",
    "room_price": 2200,
    "room_residence_ref_id": 11,
    "room_trading_price": 2000,
    "room_type": "Double",
    "is_active" : true,
    "room_area": "195 sq.ft",
    "room_capacity": 2,
    "room_quantity": 1
  }

 
]
